# Generated by Django 5.2.8 on 2025-11-07 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique primary key for this object.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('name', models.CharField(help_text='The full name of the organisation.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly short name for the organisation.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the organisation account is active.')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique primary key for this object.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('is_org_admin', models.BooleanField(default=False, help_text='If True, the user has administrative privileges within this specific organization.')),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
            },
        ),
    ]
