# Generated by Django 5.2.8 on 2025-11-07 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this organisation record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organisation',
            field=models.ForeignKey(help_text='The organization the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(help_text='The user belonging to the organization.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='organisations.OrganizationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organisation')},
        ),
    ]
