# Generated by Django 5.2.8 on 2025-11-12 02:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique primary key for this object.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('is_org_admin', models.BooleanField(default=False, help_text='If True, the user has administrative privileges within this specific organisation.')),
                ('organisation', models.ForeignKey(help_text='The organisation the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(help_text='The user belonging to the organisation.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation Membership',
                'verbose_name_plural': 'Organisation Memberships',
                'unique_together': {('user', 'organisation')},
            },
        ),
        migrations.AlterField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', through='organisations.OrganisationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
    ]
